package org.darcy.sanguo.message;

public class Message
{
  public static final String M1000 = "账号不存在";
  public static final String M1001 = "账号已存在";
  public static final String M1002 = "注册账号失败";
  public static final String M1003 = "名字被占用，请更换名字";
  public static final String M1004 = "登陆失败";
  public static final String M1005 = "删除账号失败";
  public static final String M1006 = "名字须为1-6位";
  public static final String M1007 = "获取随机名字失败";
  public static final String M1008 = "性别选择有误";
  public static final String M1009 = "修改名字失败";
  public static final String M1010 = "元宝不足";
  public static final String M1011 = "获取背包数据失败";
  public static final String M1012 = "招募失败";
  public static final String M1013 = "招募类型错误";
  public static final String M1014 = "招募次数不正确";
  public static final String M1015 = "招募数据异常";
  public static final String M1016 = "背包已满，请先清理背包";
  public static final String M1017 = "材料不足";
  public static final String M1018 = "武将升级失败";
  public static final String M1019 = "主武将不能升级";
  public static final String M1020 = "武将已达最大等级";
  public static final String M1021 = "不能使用五星武将作为升级材料";
  public static final String M1022 = "银币不足";
  public static final String M1023 = "武将等级不能超过主角等级";
  public static final String M1024 = "战功不足";
  public static final String M1025 = "武将突破失败";
  public static final String M1026 = "武将不存在";
  public static final String M1027 = "该武将不可突破";
  public static final String M1028 = "已达到最大突破等级";
  public static final String M1029 = "主角达到{0}级才可突破";
  public static final String M1030 = "{0}合成失败";
  public static final String M1031 = "碎片不足";
  public static final String M1032 = "{0}炼化失败";
  public static final String M1033 = "该{0}不能被炼化";
  public static final String M1034 = "{0}重生失败";
  public static final String M1035 = "该{0}不能重生";
  public static final String M1036 = "道具使用失败";
  public static final String M1037 = "物品不足";
  public static final String M1038 = "物品类型错误";
  public static final String M1039 = "未达到使用条件";
  public static final String M1040 = "该物品不能使用";
  public static final String M1041 = "需主角等级达到{0}级才可操作";
  public static final String M1042 = "道具不足，使用{0}个{1}需要{2}个{3}";
  public static final String M1043 = "更换武将失败";
  public static final String M1044 = "{0}级开启";
  public static final String M1045 = "该武将已上阵";
  public static final String M1046 = "获取信息失败";
  public static final String M1047 = "经验不足";
  public static final String M1048 = "精力不足";
  public static final String M1049 = "体力不足";
  public static final String M1050 = "类型错误";
  public static final String M1051 = "该武将已是副将";
  public static final String M1052 = "更换副将失败";
  public static final String M1053 = "调整布阵失败";
  public static final String M1054 = "出售物品不存在";
  public static final String M1055 = "背包扩展失败";
  public static final String M1056 = "该背包无需扩展";
  public static final String M1057 = "装备强化失败";
  public static final String M1058 = "装备不存在";
  public static final String M1059 = "装备已达最大等级";
  public static final String M1060 = "装备洗炼失败";
  public static final String M1061 = "装备尚未进行洗炼";
  public static final String M1062 = "魂玉不足，炼化5星及以上武将获得更多魂玉";
  public static final String M1063 = "请先卸下{0}再进行操作";
  public static final String M1064 = "已有该武将上阵或作为副将";
  public static final String M1065 = "装备失败";
  public static final String M1066 = "该武将未上阵";
  public static final String M1067 = "卸下装备失败";
  public static final String M1068 = "该装备已在背包里";
  public static final String M1069 = "武将达到{0}级才可突破";
  public static final String M1070 = "宝物强化失败";
  public static final String M1071 = "宝物不存在";
  public static final String M1072 = "宝物已达最大等级";
  public static final String M1073 = "材料数量异常";
  public static final String M1074 = "材料不存在";
  public static final String M1075 = "不能使用已装备的宝物做材料";
  public static final String M1076 = "紫色品质及以上的装备才可进行洗炼";
  public static final String M1077 = "该宝物已在背包里";
  public static final String M1078 = "宝物精炼失败";
  public static final String M1079 = "宝物已达最大精炼等级";
  public static final String M1080 = "只有紫色品质及以上的宝物才可进行精炼";
  public static final String M1081 = "荣誉不足，参与争霸赛能够获得更多荣誉";
  public static final String M1082 = "数据异常";
  public static final String M1083 = "争霸赛时间为每周一到周六的8:00-23:00";
  public static final String M1084 = "今日次数已用完";
  public static final String M1085 = "处于冷却中，无法刷新";
  public static final String M1086 = "挑战失败";
  public static final String M1087 = "该玩家不在你的挑战列表中";
  public static final String M1088 = "获取兑换中心信息失败";
  public static final String M1089 = "兑换失败";
  public static final String M1090 = "兑换数据不存在";
  public static final String M1091 = "兑换次数不足，无法兑换";
  public static final String M1092 = "声望不足，您可在竞技场或世界Boss战中获得声望";
  public static final String M1093 = "发奖时间，不能挑战";
  public static final String M1094 = "你不能挑战该玩家";
  public static final String M1095 = "免战失败";
  public static final String M1096 = "夺宝时间为10:00-24:00";
  public static final String M1097 = "夺宝失败";
  public static final String M1098 = "你不能抢夺该玩家";
  public static final String M1099 = "该宝物的可合成次数为0，不能抢夺";
  public static final String M1100 = "宝物强化预览失败";
  public static final String M1101 = "该玩家正处于免战状态，不能抢夺";
  public static final String M1102 = "该玩家不能被抢夺";
  public static final String M1103 = "材料与强化宝物类型不一致";
  public static final String M1104 = "不能将被强化的宝物作为强化材料";
  public static final String M1105 = "请求装备洗炼消耗失败";
  public static final String M1106 = "挑战活动副本失败";
  public static final String M1107 = "活动副本不存在";
  public static final String M1108 = "活动副本类型错误";
  public static final String M1109 = "活动副本校验失败";
  public static final String M1110 = "尚未挑战活动副本";
  public static final String M1111 = "活动副本数据异常";
  public static final String M1112 = "讨伐黄巾尚未开启";
  public static final String M1113 = "你抢夺的不是碎片,想捣乱是吧";
  public static final String M1114 = "金书银马尚未开启";
  public static final String M1115 = "领奖失败";
  public static final String M1116 = "奖励不存在或已过期";
  public static final String M1117 = "查看玩家信息失败";
  public static final String M1118 = "该玩家不存在";
  public static final String M1119 = "兑换次数有误";
  public static final String M1120 = "该物品不可出售";
  public static final String M1121 = "物品每次最多使用50个";
  public static final String M1122 = "消息结构错误";
  public static final String M1123 = "未到达领取奖励等级";
  public static final String M1124 = "今天已签到";
  public static final String M1125 = "还未到煮酒时间";
  public static final String M1126 = "已经煮过酒了，请下次再来";
  public static final String M1127 = "阵法点不足，无法领悟";
  public static final String M1128 = "阵法已全部领悟且达到最高级";
  public static final String M1129 = "尚未领悟阵法，无需重置";
  public static final String M1130 = "尚未领悟该阵法， 无法选择";
  public static final String M1131 = "尚未完成该任务";
  public static final String M1132 = "该军团名字已被使用，请输入其他名称";
  public static final String M1133 = "您已加入一个军团!";
  public static final String M1134 = "您尚未加入军团!";
  public static final String M1135 = "您无权修改军团公告";
  public static final String M1136 = "军团公告长度必须在{0}字以内";
  public static final String M1137 = "只有团长才可以进行操作";
  public static final String M1138 = "只能让位给副团长";
  public static final String M1140 = "没有找到该军团";
  public static final String M1141 = "军团名称长度必须在{0}字以内";
  public static final String M1142 = "操作失败，请稍后再试";
  public static final String M1143 = "副团长数量已达上限，不能任命";
  public static final String M1144 = "您已被{0}解除了{1}的副团长职务";
  public static final String M1145 = "您已被{0}任命为{1}的副团长";
  public static final String M1146 = "该玩家尚未加入军团";
  public static final String M1147 = "不能对团长进行操作";
  public static final String M1148 = "团长不能退出军团，请让位后继续操作";
  public static final String M1149 = "您已被踢出了【{0}】军团";
  public static final String M1150 = "您刚退出了一个军团，{0}小时后才能申请加入军团!";
  public static final String M1151 = "该军团人数已达上限，请稍后再试!";
  public static final String M1152 = "该军团申请人数过多，请稍后再试!";
  public static final String M1153 = "最多同时向{0}个军团发出申请";
  public static final String M1154 = "您申请的军团不存在";
  public static final String M1155 = "您已申请过加入该军团";
  public static final String M1156 = "您无权进行该操作";
  public static final String M1157 = "该玩家已在军团中";
  public static final String M1158 = "该玩家已取消申请或已加入其他军团";
  public static final String M1159 = "您加入{0}的申请被拒绝了";
  public static final String M1160 = "没有该类型的军团建设";
  public static final String M1161 = "今天已经建设过，请明天再来";
  public static final String M1162 = "碎片不存在";
  public static final String M1163 = "需要等级达到{0}级才可以攻打";
  public static final String M1164 = "需要通关{0}";
  public static final String M1165 = "你今天已领取过物资";
  public static final String M1166 = "贡献不足，无法领取物资";
  public static final String M1167 = "该商品已兑换完，请下次再来";
  public static final String M1168 = "贡献不足，无法兑换";
  public static final String M1169 = "军团等级尚未达到，无法兑换";
  public static final String M1170 = "军团设施不存在";
  public static final String M1171 = "该军团设施尚未开放";
  public static final String M1172 = "军团大厅已达最大等级";
  public static final String M1173 = "其他设施等级不能超过大厅等级";
  public static final String M1174 = "军团建设不足";
  public static final String M1175 = "你不能领取该奖励";
  public static final String M1176 = "官银兑换次数不足，请明天再来";
  public static final String M1177 = "你已经拥有了该碎片，无法抢夺";
  public static final String M1178 = "你已购买过成长计划";
  public static final String M1179 = "你尚未购买成长计划";
  public static final String M1180 = "活动尚未开启或已结束";
  public static final String M1181 = "该活动已达上限";
  public static final String M1182 = "<p style=13>[{0}]</p><p style=17>在七星坛召唤了十次神将，召唤出了</p><p style=15>[{1}]</p><p style=17>，争霸天下指日可待！</p>";
  public static final String M1183 = "<p style=17>铜雀化身已降临，请各路诸讨伐铜雀化身！</p>";
  public static final String M1184 = "<p style=17>在</p><p style=15>軍團【{0}】</p><p style=17>的帶領下，銅雀化身最終被擊退了！</p>";
  public static final String M1185 = "<p style=17>（本次铜雀化身的最终击杀者是</p><p style=13>{0}</p><p style=17>！）</p>";
  public static final String M1186 = "<p style=13>[{0}]</p><p style=17>在竞技场中成功击败了</p><p style=13>[{1}]</p><p style=17>取得了第{2}名！</p>";
  public static final String M1187 = "<p style=17>本周争霸赛快报，目前积分最高的三名玩家分别是</p><p style=13>{0}</p><p style=17>！</p>";
  public static final String M1188 = "<p style=17>本周争霸赛已结束，获得前三名的玩家分别是</p><p style=13>{0}</p><p style=17>！</p>";
  public static final String M1189 = "<p style=13>[{0}]</p><p style=17>创建了军团</p><p style=13>[{1}]</p><p style=17>，邀请广大志同道合的朋友加入！</p>";
  public static final String M1190 = "<p style=13>[{0}]</p><p style=17>成功把</p><p style=14>[{1}]</p><p style=17>突破到+{2}，实力大幅度的提高了！</p>";
  public static final String M1191 = "不能使用该物品作为材料";
  public static final String M1192 = "尚未充值";
  public static final String M1193 = "无需购买";
  public static final String M1194 = "购买次数已达上限";
  public static final String M1195 = "<p style=13>[{0}]</p><p style=17>人品爆发，开启金宝箱时获得了</p><p style=15>{1}</p><p style=17>，真是羡煞旁人。</p>";
  public static final String M1196 = "VIP等级不足";
  public static final String M1197 = "账号已被封停，如有异议请联系客服处理";
  public static final String M1198 = "没有该积分对应的奖励";
  public static final String M1199 = "未获得奖励对应积分数";
  public static final String M1200 = "幸运转盘抽取次数不正确";
  public static final String M1201 = "剩余次数不足";
  public static final String M1202 = "<p style=13>[{0}]</p><p style=17>人品爆发，祈福时获得了</p><p style=15>{1}</p><p style=17>，真是羡煞旁人。</p>";
  public static final String M1203 = "在{0}天后可再次购买。";
  public static final String M1204 = "您尚未获得光环";
  public static final String M1205 = "该光环已被使用";
  public static final String M1206 = "该光环已达最大等级";
  public static final String M1207 = "过关斩将扫荡奖励";
  public static final String M1208 = "<p style=21>恭喜主公，您在过关斩将中对</p><p style=20>【{0}】</p><p style=21>至</p><p style=20>【{1}】</p><p style=21>进行了扫荡，获得奖励如下：</p>";
  public static final String M1209 = "月卡每日奖励";
  public static final String M1210 = "<p style=21>尊敬的主公，呈上今天的</p><p style=19>【{0}】</p><p style=21>每日奖励，请您笑纳。\n温馨提醒：月卡剩余</p><p style=20>【{1}】</p><p style=21>天。</p>";
  public static final String M1211 = "该光环无需重置";
  public static final String M1212 = "背包格数已达上限，无法继续购买";
  public static final String M1213 = "充值异常，请联系客服处理";
  public static final String M1214 = "无人申请加入军团";
  public static final String M1215 = "您尚未申请加入该军团";
  public static final String M1216 = "主公等级达{0}级或VIP等级达{1}级才可进行此操作";
  public static final String M1217 = "<p style=21>【{0}】成功使用了</p><p style=19>【{1}】</p><p style=21>军团建设！</p>";
  public static final String M1218 = "您已购买过该商品";
  public static final String M1219 = "军团Boss奖励";
  public static final String M1220 = "<p style=21>恭喜主公，昨日您所在军团【{0}】的军团Boss的最高等级为</p><p style=19>【{1}】</p><p style=21>。另外，主公对军团Boss造成了</p><p style=19>【{2}】</p><p style=21>的总伤害量，排名军团第</p><p style=20>【{3}】</p><p style=21>名。</p>\n<p style=21>根据昨日Boss最高等级以及您的军团伤害排名情况，现为您颁发以下奖励：</p>";
  public static final String M1221 = "<p style=21>恭喜主公，昨日您在军团</p><p style=19>【{0}】</p><p style=21>中对军团Boss造成</p><p style=19>【{1}】</p><p style=21>的总伤害量。</p>\n<p style=21>根据昨日Boss最高等级以及您的军团伤害排名情况，现为您颁发以下奖励：</p>";
  public static final String M1222 = "军团boss尚未开启";
  public static final String M1223 = "正在冷却，不能挑战boss";
  public static final String M1224 = "boss尚未复活，请稍等";
  public static final String M1225 = "大家一起来建设军团吧！";
  public static final String M1226 = "<p style=21>很抱歉，您已被军团</p><p style=20>【{0}】</p><p style=21>的相关管理人员踢出军团~~\n抛弃你将是他们的损失！！快加入其他军团，证明你的实力吧！！</p>";
  public static final String M1227 = "充值渠道不存在";
  public static final String M1228 = "您尚未购买月卡，无法升级季卡";
  public static final String M1229 = "季卡每日奖励";
  public static final String M1230 = "<p style=21>尊敬的主公，呈上今天的</p><p style=19>【{0}】</p><p style=21>每日奖励，请您笑纳。\n温馨提醒：季卡剩余</p><p style=20>【{1}】</p><p style=21>天。</p>";
  public static final String M1231 = "已达最大VIP等级";
  public static final String M1232 = "月卡奖励返还补偿";
  public static final String M1233 = "<p style=21> 主公那么挺我们！月月包月，没道理我们不回馈给大家~ 所以月卡的每天获得元宝奖励，我们调整了!过去已领取的我们一样返还差额元宝给您!!感谢您对于我们的支持！祝主公游玩愉快~ </p>";
  public static final String M1234 = "成长计划返还补偿";
  public static final String M1235 = "<p style=21> 只要我长大！每一级都是主公努力获得，成长计划成为您最佳目标！这次我们也将成长计划调整了~ 过去已达成领取过的的我们会返还差额元宝；至于尚在努力达成目标的主公们，达到目标后就可以领到调整后的元宝奖励噜~</p>";
  public static final String M1236 = "装备已达最大铸造等级";
  public static final String M1237 = "该装备无法铸造";
  public static final String M1238 = "<p style=21>尊敬的主公，这是今天的</p><p style=19>【{0}】</p><p style=21>每日奖励，请您笑纳。\n温馨提示：您的月卡还剩余</p><p style=20>【{1}】</p><p style=21>天</p>";
  public static final String M1239 = "加送{0}元宝（三倍）";
  public static final String M1240 = "好评返利";
  public static final String M1241 = "<p style=21>感谢您对</p><p style=20>《三国吧！兄弟》</p><p style=21>的大力支持！您的好评是对我们最大的肯定！我们将继续努力提高游戏品质，完善游戏体验！也欢迎您继续给予我们支持与建议。</p>";
  public static final String M1242 = "删除账号失败，请稍后再试";
  public static final String M1243 = "机关人";
  public static final String M1244 = "<p style=13>[{0}]</p><p style=17>成功把</p><p style=14>[{1}]</p><p style=17>觉醒到+{2}，实力大幅度的提高了！</p>";
  public static final String M1245 = "【铜雀魔神】军团伤害排行奖励";
  public static final String M1246 = "<p style=21>恭喜主公，您所在的军团【{0}】在今日的铜雀魔神挑战中对Boss造成了</p><p style=19>【{1}】</p><p style=21>的总伤害量，获得军团第</p><p style=20>【{2}】</p><p style=21>排名的好成绩。\n根据军团伤害总量排名，本次获得的军团排名奖励如下：</p>";
  public static final String M1247 = "开启条件：";
  public static final String M1248 = "冷却时间未到，无法操作";
  public static final String M1249 = "订单处理中，请稍后";
  public static final String M1250 = "首充补偿";
  public static final String M1251 = "<p style=21>为感谢广大玩家对游戏的大力支持，我们调整了11000首冲礼包的首充额度到5500韩元。由于您已满足该礼包获得条件，现为您补发该礼包，奖励内容如下：</p>";
  public static final String M1252 = "<p style=21>为感谢广大玩家对游戏的大力支持，我们调整了11000首冲礼包的首充额度到5500韩元。原首次购买</p><p style=20>11000首充礼包</p><p style=21>的玩家，我们将为您补偿以下奖励：</p>";
  public static final String M1253 = "战斗录像不存在";
  public static final String M1254 = "战魂不足";
  public static final String M1255 = "战魂";
  public static final String M1256 = "跨服战淘汰赛奖励";
  public static final String M1257 = "<p style=21>主公在此次跨服战中获胜</p><p style=20>{0}</p><p style=21>场，获得战魂</p><p style=19>{1}</p>";
  public static final String M1258 = "<p style=21>主公在此次跨服战中获胜</p><p style=20>{0}</p><p style=21>场，第</p><p style=20>{1}</p><p style=21>场失败，获得战魂</p><p style=19>{2}</p>";
  public static final String M1259 = "跨服战全民福利";
  public static final String M1260 = "<p style=20>{0}(</p><p style=19>{1}</p><p style=20>) </p>";
  public static final String M1261 = "冠军";
  public static final String M1262 = "亚军";
  public static final String M1263 = "四强";
  public static final String M1264 = "八强";
  public static final String M1265 = "十六强";
  public static final String M1266 = "<p style=21>在第</p><p style=20>【{0}】</p><p style=21>届跨服战中，玩家</p>{1}<p style=21>，为全服带来荣誉，全服获得</p><p style=19>【{2}】</p><p style=21>战魂奖励，请大家为他们欢呼吧！</p>";
  public static final String M1267 = "第{0}届跨服战战报";
  public static final String M1268 = "<p style=21>第</p><p style=20>【{0}】</p><p style=21>届跨服战的最终冠军是</p><p style=20>【{1}】</p><p style=21>服的</p><p style=20>【{2}】</p><p style=21>。您所在的服务器中，以下玩家取得了非凡的成绩，他们是</p>{3}<p style=21>，让我们为他们欢呼吧！</p>";
  public static final String M1269 = "<p style=21>第</p><p style=20>【{0}】</p><p style=21>届跨服战的最终冠军是</p><p style=20>【{1}】</p><p style=21>服的</p><p style=20>【{2}】</p><p style=21>，您所在服务器中没有玩家进入决赛阶段，主公们还需继续努力！</p>";
  public static final String M1270 = "<p style=21>上届跨服战的冠军</p><p style=20>{0}</p><p style=21>上线了，欢呼声在哪里！！！</p>";
  public static final String M1271 = "<p style=21>恭喜主公在</p><p style=20>【{0}】</p><p style=21>届跨服战中，取得</p><p style=20>{1}</p><p style=21>的好成绩，继续努力，让您的威名让全天下人都知晓吧！</p>";
  public static final String M1272 = "跨服战决赛奖励";
  public static final String M1273 = "<p style=17>（本次銅雀化身的最終擊殺者是</p><p style=15>軍團【{0}】</p><p style=17>的</p><p style=13>{1}</p><p style=17>！）</p>";
  public static final String M2001 = "已经领取过该奖励";
  public static final String M2002 = "你都没打过这个副本";
  public static final String M2003 = "积累星数不足，请通过更多普通关卡来获得星数";
  public static final String M2004 = "未到银币鼓舞时间，请耐心等待或选择元宝鼓舞";
  public static final String M2005 = "已经达到最大鼓舞等级";
  public static final String M2006 = "挑战已经关闭";
  public static final String M2007 = "死人是不会动的";
  public static final String M2008 = "地图尚未开启";
  public static final String M2009 = "挑战次数不足，请明日再来";
  public static final String M2010 = "服务器繁忙，请稍后再试";
  public static final String M2011 = "消灭全部敌人";
  public static final String M2012 = "在{0}回合内取得胜利";
  public static final String M2013 = "损失血量低于{0}%";
  public static final String M2014 = "我方阵亡武将少于{0}个";
  public static final String M2015 = "该关卡没有宝箱奖励";
  public static final String M2016 = "正在扫荡中";
  public static final String M2017 = "当前已经在最高层，请先重置";
  public static final String M2018 = "当前不在扫荡中";
  public static final String M2019 = "当前正在第一关，无需重置";
  public static final String M2020 = "今日重置次数不足";
  public static final String M2021 = "还未通关";
  public static final String M2022 = "查找玩家失败";
  public static final String M2023 = "已经给该玩家送过了";
  public static final String M2024 = "不是好友关系";
  public static final String M2025 = "今天";
  public static final String M2026 = "天前";
  public static final String M2027 = "没有该玩家赠送的精力";
  public static final String M2028 = "精力已满";
  public static final String M2029 = "不存在的好友申请";
  public static final String M2030 = "对方已经是你的好友";
  public static final String M2031 = "申请已提交";
  public static final String M2033 = "查找的玩家不存在";
  public static final String M2034 = "今日挑战次数已经用完，请重置或明天再来";
  public static final String M2035 = "已经达到最天命等级";
  public static final String M2036 = "剩余星数不足，请通过更多普通关卡来获得星数";
  public static final String M2037 = "击败所有敌人";
  public static final String M2038 = "扫荡中，不能重置";
  public static final String M2039 = "扫荡中，不能挑战";
  public static final String M2040 = "自身好友人数达到上限，无法申请";
  public static final String M2041 = "对方好友申请人数达到上限，无法申请";
  public static final String M2042 = "地图还未开通";
  public static final String M2043 = "扫荡时间未到";
  public static final String M2044 = "卜卦次数已用完";
  public static final String M2045 = "还未收卦";
  public static final String M2046 = "还未占卜";
  public static final String M2047 = "占卜还未升级";
  public static final String M2048 = "没有更多邮件了";
  public static final String M2049 = "该奇策尚未学习";
  public static final String M2050 = "该奇策已达最高等级";
  public static final String M2051 = "刷新次数不足";
  public static final String M2052 = "没有可领取的奖励";
  public static final String M2053 = "未被击杀";
  public static final String M2054 = "不能给自己发邮件";
  public static final String M2056 = "<p style=19>{0}</p><p style=21>在竞技场中向你发起挑战，你被击败了，排名降至</p><p style=20>{1}</p><p style=21>名。这你能忍？快去复仇吧！</p>";
  public static final String M2058 = "人物等级达到{0}级才可升级";
  public static final String M2059 = "该物品不能赠送";
  public static final String M2060 = "该小兵毫无名气，不能给他赠送";
  public static final String M2061 = "名将历练已经达到最高级，无法继续培养";
  public static final String M2062 = "主角达到10级就能发世界消息啦";
  public static final String M2063 = "30级以下玩家，每天发送消息数不能超过5条";
  public static final String M2064 = "人物精力上限+{0}";
  public static final String M2065 = "信息发送过于频繁，请稍后再试";
  public static final String M2066 = "发送信息长度必须介于1~100字符之间";
  public static final String M2070 = "荣誉";
  public static final String M2072 = "元宝";
  public static final String M2073 = "银币";
  public static final String M2074 = "经验";
  public static final String M2075 = "声望";
  public static final String M2076 = "魂玉";
  public static final String M2077 = "耐力";
  public static final String M2079 = "体力";
  public static final String M2080 = "将魂";
  public static final String M2081 = "关卡尚未开放";
  public static final String M2082 = "阵法点数";
  public static final String M2083 = "不存在该武将";
  public static final String M2084 = "该武将机缘已经升级";
  public static final String M2085 = "升级机缘需要武将升级到{0}级";
  public static final String M2086 = "请先升级机缘";
  public static final String M2087 = "已经兑换过该类礼包";
  public static final String M2088 = "版本号过低，重启更新客户端";
  public static final String M2089 = "加送{0}元宝（双倍）";
  public static final String M2090 = "加送{0}元宝";
  public static final String M2091 = "不存在的订单";
  public static final String M2092 = "订单不属于自己";
  public static final String M2093 = "你买的东西貌似已经下架了，客服MM会帮你搞定";
  public static final String M2094 = "重复验证";
  public static final String M2095 = "每天可以领取奖励：{0}";
  public static final String M2096 = "精英副本每天可以购买{0}次挑战次数";
  public static final String M2097 = "千年树妖每天可以购买{0}次挑战次数";
  public static final String M2098 = "讨伐黄巾每天可以购买{0}次挑战次数";
  public static final String M2099 = "金书银马每天可以购买{0}次挑战次数";
  public static final String M2100 = "每天可以进行官银兑换{0}次";
  public static final String M2101 = "神秘商店每天可元宝刷新{0}次";
  public static final String M2102 = "过关斩将每天可购买{0}次失败挑战次数";
  public static final String M2103 = "争霸赛每天可购买{0}次挑战次数";
  public static final String M2104 = "每天可购买{0}";
  public static final String M2105 = "普通副本每天可重置{0}次挑战次数";
  public static final String M2106 = "当前VIP等级无每日奖励可领取";
  public static final String M2107 = "今天的奖励已经领取过，请明日再来";
  public static final String M2108 = "元宝刷新次数不足，升级vip等级能提高每日刷新上限";
  public static final String M2109 = "已经达到最后一关";
  public static final String M2110 = "已经购买过该礼包";
  public static final String M2112 = "登录状态过期，请重新登陆";
  public static final String M2113 = "占卜奖励每天可元宝刷新{0}次";
  public static final String M2114 = "已经学习了该奇策";
  public static final String M2115 = "未到该奇策学习等级";
  public static final String M2116 = "服务器爆满，请稍后重新登录";
  public static final String M2117 = "当前没有可领取的奖励，不能刷新";
  public static final String M2118 = "昨天";
  public static final String M2119 = "前天";
  public static final String M2120 = "您不能添加自己为好友";
  public static final String M2121 = "订单错误";
  public static final String M2122 = "订单尝试次数过多";
  public static final String M2123 = "已经达到最大卦数，请明天再来";
  public static final String M2124 = "来自“{0}”的留言";
  public static final String M2125 = "邮件不存在";
  public static final String M2126 = "没有附件";
  public static final String M2127 = "<p style=21>恭喜主公，截止到今天22:00,您在竞技场中获得第</p><p style=20>{0}</p><p style=21>排名的好成绩，获得奖励如下：</p>";
  public static final String M2128 = "竞技场每日排名奖励";
  public static final String M2129 = "竞技场被击败";
  public static final String M2130 = "宝物碎片被抢夺";
  public static final String M2131 = "<p style=19>{0}</p><p style=21>在夺宝中成功掠夺你的</p><p style=19>{1}</p><p style=21>！！主公下回可要保护好自己的宝物！！</p>";
  public static final String M2132 = "争霸赛每周排名奖励";
  public static final String M2133 = "<p style=21>恭喜主公，截止到本周六23:00，您在争霸赛中获得第</p><p style=20>{0}</p><p style=21>排名的好成绩，获得奖励如下：</p>";
  public static final String M2134 = "争霸赛被击败";
  public static final String M2135 = "<p style=19>{0}</p><p style=21>在争霸赛中向你发起挑战，你被击败了，被抢夺了</p><p style=20>{1}</p><p style=21>积分。这你能忍？快去复仇吧！</p>";
  public static final String M2136 = "铜雀神魔奖励";
  public static final String M2137 = "<p style=21>恭喜主公，您在今天的铜雀魔神挑战中对Boss造成了</p><p style=19>{0}</p><p style=21>的总伤害量，获得第</p><p style=20>{1}</p><p style=21>排名的好成绩，获得奖励如下：</p>";
  public static final String M2138 = "<p style=21>恭喜主公，您在今天的铜雀魔神挑战中对Boss造成了</p><p style=19>{0}</p><p style=21>的总伤害量，获得第</p><p style=20>{1}</p><p style=21>排名的好成绩。\n并且您还完成了对Boss的最后一击，额外获得了一份击杀奖励。\n本次铜雀魔神获得奖励如下：</p>";
  public static final String M2139 = "占卜奖励补发";
  public static final String M2140 = "<p style=21>主公，您于</p><p style=20>{0}月{1}日</p><p style=21>占卜获得了</p><p style=19>{2}</p><p style=21>卦数，但未领取奖励。现为您补发奖励，请快快收下：</p>";
  public static final String M2141 = "登录状态过期，请重新登录帐号";
  public static final String M2142 = "该激活码已经使用或者已达激活次数上限";
  public static final String M2143 = "无效的激活码";
  public static final String M2144 = "激活码格式不正确";
  public static final String M2145 = "激活码已经过有效期";
  public static final String M2146 = "<p style=21>很遗憾，截止到本周六23:00，您未能在争霸赛中获得任何名次。\n作为鼓励，我们给您准备了以下奖励。下周努力再战哦~：</p>";
  public static final String M2147 = "激活码还未生效";
  public static final String M2148 = "好友已满";
  public static final String M2149 = "达到今日领取次数上限，请明日再来";
  public static final String M2150 = "对方好友已满";
  public static final String M2151 = "训练点数不足";
  public static final String M2152 = "已经达到最大训练等级";
  public static final String M2153 = "无需重置训练等级";
  public static final String M2154 = "该武将无法传承";
  public static final String M2155 = "品质不同的武将无法进行传承";
  public static final String M2156 = "每天可以免费领取训练点{0}次";
  public static final String M2157 = "达到今天最大训练次数，请明天再来";
  public static final String M2158 = "夺宝解锁一键抢夺功能";
  public static final String M2159 = "活动已经结束";
  public static final String M2160 = "七日比拼排名奖励";
  public static final String M2161 = "<p style=21>恭喜主公，截止到“七日战力比拼”活动结束，您的战力为</p><p style=19>【{0}】</p><p style=21>，全服排行第</p><p style=20>【{1}】</p><p style=21>名。获得奖励如下：</p>";
  public static final String M2162 = "尚未开启";
  public static final String M2163 = "<p style=17>“七日战力比拼”活动快报！截止目前，战力最高的三名玩家依次是</p><p style=13>{0}</p><p style=17>！ → 更多活动规则奖励详情，请到“活动中心”查看！</p>";
  public static final String M2164 = "老玩家回归福利";
  public static final String M2165 = "</p style=21>亲爱的玩家您好，您的账号已经参加过安卓删档计费测试，本次回归我们将送您一份老玩家“真情礼包”，非常感谢您一直以来对我们的支持，希望您在《三国吧兄弟》的游戏世界中快乐每一天！</p>";
  public static final String M2166 = "老玩家回归奖励";
  public static final String M2167 = "</p style=21>亲爱的玩家您好，您的账号已经参加过安卓删档计费测试并进行过充值，本次回归我们将送您一份老玩家“至尊礼包”，非常感谢您一直以来对我们的支持，希望您在《三国吧兄弟》的游戏世界中快乐每一天！</p>";
  public static final String M2168 = "充值返还";
  public static final String M2169 = "</p style=21>亲爱的玩家你好，您在上次安卓删档计费测试累计充值{0}元宝，达到VIP{1}级，本次回归我们将给您全额返还，非常感谢您一直以来对我们的支持，希望您在《三国吧兄弟》的游戏世界中快乐每一天！</p>";
  public static final String M2170 = "超级返利第{0}天";
  public static final String M2171 = "</p style=21>亲爱的玩家您好，您在上次安卓删档计费测试累计充值{0}元宝，超值返利的50%元宝返还部分，我们会在首日返还10%，第二日返还10%，第三日返还20%，第四日返还10%，第五日返还10%，第六日返还10%，第七日返还30%，非常感谢您一直以来对我们的支持！</p>";
  public static final String M2172 = "活动尚未结束，不能领奖";
  public static final String M2173 = "有料版限定の特典";
  public static final String M2174 = "<p style=21>有料版乱闘三国のご購入ありがとうございます。感謝の気持ちを込めて</p><p style=20>有料版限定特典</p><p style=21>をお送りいたします。</p>";
  public static final String M2175 = "该副将站位已经解锁";
  public static final String M2176 = "请按顺序解锁";
  public static final String M2177 = "未解锁的副将站位";
  public static final String M2178 = "未开启的副将站位";
  public static final String M2179 = "珍品商店每日可刷新{0}次";
  public static final String M2180 = "献花次数不足，请明日再来";
  public static final String M2181 = "此處不可達";
  public static final String M2182 = "請先完成此處事件";
  public static final String M2183 = "沒有行動力";
  public static final String M2184 = "沒有需要處理的事件";
  public static final String M2185 = "該事件已經完成";
  public static final String M2186 = "事件類型不匹配";
  public static final String M2187 = "已經達到終點，請重置尋寶或明日再來";
  public static final String M2189 = "重置次數不足，請明日再來";
  public static final String M2190 = "自動探索只能在起點進行";
  public static final String M2191 = "達到行動力購買上限，請明日再來";
  public static final String M2192 = "玄兵尋寶積分不足";
  public static final String M2193 = "玄兵尋寶積分";
  public static final String M2194 = "還未進行尋寶，請尋寶後再進行重置";
  public static final String M2195 = "限时抽卡尚未开启";
  public static final String M2196 = "邮件已发送，客服收到邮件后会与您联系";
  public static final String M2197 = "发送邮件过于频繁，请1分钟之后再试";
  public static final String M2198 = "充值排行活动";
  public static final String M2199 = "<p style=21>充值排行活动</p><p style=20></p><p style=21>正在火热进行中，目前排名前三玩家分别为</p><p style=19>{0}</p><p style=21>！！</p>\t";
  public static final String M2200 = "<p style=21>本次充值排行活动</p><p style=20></p><p style=21>即将结束，目前排名前三玩家分别为</p><p style=19>{0}</p><p style=21>！！</p>";
  public static final String M2201 = "<p style=21>次充值排行活动</p><p style=20></p><p style=21>已经结算，本次活动排名前三玩家分别为</p><p style=19>{0}</p><p style=21>！！快来膜拜大神吧！！</p>";
  public static final String M2202 = "充值排行榜活动已经结束";
  public static final String M2203 = "<p style=21>恭喜主公，在本次充值排行活动</p><p style=20>（{0}-{1}）</p><p style=21>中获得了排名第</P><p style=19>【{2}】</p><p style=21>的好成绩，获得如下奖励：</p>";
  public static final String M2204 = "职位变动";
  public static final String M2205 = "</p style=21>你对军团的不作为，使你在军团中的职位变更为团员。新团长为</p><p style=20>【{0}】</p>";
  public static final String M2206 = "</p style=21>你对军团的劳心劳力，使你在军团中的职位变更为团长。</p>";
  public static final String M2207 = "本轮你已经抽奖，请等团长大人刷新后再来";
  public static final String M2208 = "该奖励已经被抽走，请换一个吧";
  public static final String M2209 = "贡献值不足,不能抽奖";
  public static final String M2210 = "等级达到15级才能发送邮件";
  public static final String M2211 = "军团战已经结束";
  public static final String M2212 = "周一至周五零点，成员数达20人的军团才可参与匹配";
  public static final String M2213 = "该城池已经有主";
  public static final String M2214 = "无主城池，请直接占领即可";
  public static final String M2215 = "城池已经易主，请重新发起挑战";
  public static final String M2216 = "请耐心等待复活";
  public static final String M2217 = "对方军团全都龟缩城内，去嘲讽他吧";
  public static final String M2218 = "轮空";
  public static final String M2219 = "军团战奖励";
  public static final String M2220 = "<p style=21>恭喜主公，您的所在军团</p><p style=77>【{0}】</p><p style=21>在本轮军团战中战胜了军团</p><p style=76>【{1}】</p><p style=21>，鉴于您的卓越贡献，将获得以下奖励：</p>";
  public static final String M2221 = "<p style=21>很遗憾！本轮军团战中，军团</p><p style=76>【{0}】</p><p style=21>战胜了您的所在军团</p><p style=77>【{1}】</p><p style=21>。鉴于您的卓越贡献，将获得以下奖励：</p>";
  public static final String M2222 = "<p style=77>【{0}】</p><p style=21>成功击败【{1}】，帮助军团获得了</p><p style=84>【{2}】</p><p style=21>的占领权！</p>";
  public static final String M2223 = "<p style=84>【{0}】</p><p style=21>失守！！</p><p style=21>目前正被敌军</p><p style=76>【{1}】</p><p style=21>占领！！</p>";
  public static final String M2224 = "魏";
  public static final String M2225 = "蜀";
  public static final String M2226 = "吴";
  public static final String M2227 = "群";
  public static final String M2228 = "主城";
  public static final String M2229 = "副城";
  public static final String M2230 = "小城";
  public static final String M2231 = "<p style=77>我军</p><p style=21>累计资源已达</p><p style=19>【1500】</p><p style=21>！！加油！胜利就在眼前！！</p>";
  public static final String M2232 = "<p style=76>敌军</p><p style=21>累计资源已达</p><p style=19>【1500】</p><p style=21>！！</p>";
  public static final String M2233 = "军团战排名奖励";
  public static final String M2234 = "<p style=21>恭喜主公，您的所在军团</p><p style=20>【{0}】</p><p style=21>在本届军团战中获得了</p><p style=19>{1}</p><p style=21>积分、</p><p style=20>{2}</p><p style=21>净胜资源的好成绩。排名第</p><p style=20>【{3}】</p><p style=21>，为了感谢您对军团的突出贡献，现为您颁发以下奖励：</p>";
  public static final String M2235 = "<p style=21>第</p><p style=19>【{0}】</p><p style=21>届军团战激战正酣！！</p><p style=21>目前积分排名前三的军团分别是</p><p style=20>【{1}】</p>";
  public static final String M2236 = "<p style=21>第</p><p style=19>【{0}】</p><p style=21>届军团战落下帷幕，本届冠军为军团长</p><p style=20>{1}</p><p style=21>带领的军团</p><p style=20>【{2}】</p><p style=21>！！</p>";
  public static final String M3001 = "该武将不可觉醒";
  public static final String M3002 = "已达到最大觉醒等级";
  public static final String M3003 = "觉醒丹数量不足";
  public static final String M3004 = "请求武将觉醒信息失败";
  public static final String M3005 = "武将融合失败";
  public static final String M3006 = "需要武将融合等级达到{0}级";
  public static final String M3101 = "军团Boss Lv.{0}击杀奖励";
  public static final String M3102 = "<p style=21>您的所在军团</p><p style=20>【{0}】</p><p style=21>又一次击败了军团Boss，现为您颁发\"{1} Lv.{2}击杀奖励\"：</p>";
  public static final String M3103 = "军团Boss击杀奖励（周）";
  public static final String M3104 = "<p style=21>本周，您的所在军团</p><p style=20>【{0}】</p><p style=21>共击杀军团Boss</p></p style=19>{1}</p><p style=21>次。\n根据本周击杀次数，全军团成员将获得以下奖励：</p>";
  public static final String M3110 = "<p style=13>[{0}]</p><p style=17>人品爆发，在【活动：地藏探宝】中获得了</p><p style=15>{1}</p><p style=17>，真是羡煞旁人。</p>";
  public static final String M3501 = "<p style=21>恭喜玩家</p><p style=16>{0}</p><p style=21>，全服第一个击杀了过关斩将中的</p><p style=20>{1}</p><p style=21>，成为首个获得官职{2}的玩家</p>";
  public static final String M3502 = "天天好礼未领取奖励补发";
  public static final String M3503 = "<p style=21>您有天天好礼奖励未领取，由于活动更新，我们将您未领取的奖励邮寄给您，请确认查收！</p>";
  public static final String M3201 = "好感度の上限に達しました。";
}
